# set up trutle
import turtle as trtl

mytrtl = trtl.Turtle()

# set up stickman
print("Make a Stckman")
thicc = int(input("How thick shold the outline be? "))
print("The thickness is now", thicc,)
color = input("What should the main color be? ")
print("The color is now", color,)
outline = input("What should the outline color be? ")
print("The outline is now the color", outline,)
head = int(input("How big should the head be? "))
print("The head size is now", head,)

# draw stickman
print("Making stickman...")
mytrtl.pensize(thicc)
mytrtl.color(color)
mytrtl.pencolor(outline)
mytrtl.up()
mytrtl.goto(0, 0)
mytrtl.down()
mytrtl.rt(90)
mytrtl.fd(100)
mytrtl.rt(30)
mytrtl.fd(100)
mytrtl.lt(30)
mytrtl.up()
mytrtl.goto(0, -100)
mytrtl.down()
mytrtl.lt(30)
mytrtl.fd(100)
mytrtl.rt(30)
mytrtl.up()
mytrtl.goto(0, 0)
mytrtl.down()
mytrtl.rt(30)
mytrtl.fd(100)
mytrtl.lt(30)
mytrtl.up()
mytrtl.goto(0, 0)
mytrtl.down()
mytrtl.lt(30)
mytrtl.fd(100)
mytrtl.rt(30)
mytrtl.up()
mytrtl.goto(0, 0)
mytrtl.down()
mytrtl.lt(90)
mytrtl.begin_fill()
mytrtl.circle(head)
mytrtl.end_fill()
print("Your stickman has been made")

wn = trtl.Screen()
wn.mainloop()